package dao;

import util.DBUtil;
import java.sql.*;
import java.util.ArrayList;
import java.util.List;

/**
 * Data Access Object (DAO) for System Message operations.
 * 
 * <p>This class provides database operations for system-generated messages,
 * such as low stock alerts. System messages are used to notify owners about
 * important system events that require attention.
 * 
 * <p>Features:
 * <ul>
 *   <li>System message CRUD operations</li>
 *   <li>Low stock alert creation</li>
 *   <li>Read/unread status tracking</li>
 *   <li>Unread message counting</li>
 *   <li>Automatic low stock alert checking</li>
 * </ul>
 * 
 * @author GreenGrocer Team
 * @version 1.0
 */
public class SystemMessageDAO {

    /**
     * Inner class representing a system message.
     * 
     * <p>System messages are generated by the system to notify owners about
     * important events, such as low stock alerts.
     * 
     * @author GreenGrocer Team
     * @version 1.0
     */
    public static class SystemMessage {
        /**
         * The unique identifier for this system message.
         */
        private int id;
        
        /**
         * The type of system message (e.g., "LOW_STOCK").
         */
        private String messageType;
        
        /**
         * The title of the message.
         */
        private String title;
        
        /**
         * The message content.
         */
        private String message;
        
        /**
         * The ID of the related product (if applicable, null otherwise).
         */
        private Integer relatedProductId;
        
        /**
         * The timestamp when this message was created.
         */
        private Timestamp createdAt;
        
        /**
         * Whether this message has been read.
         */
        private boolean isRead;

        /**
         * Constructor for SystemMessage.
         * 
         * @param id The unique identifier
         * @param messageType The message type
         * @param title The message title
         * @param message The message content
         * @param relatedProductId The related product ID (null if not applicable)
         * @param createdAt The creation timestamp
         * @param isRead Whether the message has been read
         */
        public SystemMessage(int id, String messageType, String title, String message,
                Integer relatedProductId, Timestamp createdAt, boolean isRead) {
            this.id = id;
            this.messageType = messageType;
            this.title = title;
            this.message = message;
            this.relatedProductId = relatedProductId;
            this.createdAt = createdAt;
            this.isRead = isRead;
        }

        /**
         * Gets the message ID.
         * 
         * @return The message ID
         */
        public int getId() {
            return id;
        }

        /**
         * Gets the message type.
         * 
         * @return The message type
         */
        public String getMessageType() {
            return messageType;
        }

        /**
         * Gets the message title.
         * 
         * @return The title
         */
        public String getTitle() {
            return title;
        }

        /**
         * Gets the message content.
         * 
         * @return The message content
         */
        public String getMessage() {
            return message;
        }

        /**
         * Gets the related product ID.
         * 
         * @return The product ID, or null if not applicable
         */
        public Integer getRelatedProductId() {
            return relatedProductId;
        }

        /**
         * Gets the creation timestamp.
         * 
         * @return The creation timestamp
         */
        public Timestamp getCreatedAt() {
            return createdAt;
        }

        /**
         * Checks if the message has been read.
         * 
         * @return true if read, false otherwise
         */
        public boolean isRead() {
            return isRead;
        }
    }

    /**
     * Gets all system messages.
     * 
     * <p>Retrieves all system messages from the database, ordered by
     * creation date (most recent first).
     * 
     * @return A list of all system messages, ordered by created_at DESC
     */
    public static List<SystemMessage> getAllMessages() {
        List<SystemMessage> messages = new ArrayList<>();
        String sql = "SELECT * FROM SystemMessage ORDER BY created_at DESC";

        try (Connection con = DBUtil.getConnection();
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {

            while (rs.next()) {
                messages.add(new SystemMessage(
                        rs.getInt("id"),
                        rs.getString("message_type"),
                        rs.getString("title"),
                        rs.getString("message"),
                        rs.getObject("related_product_id") != null ? rs.getInt("related_product_id") : null,
                        rs.getTimestamp("created_at"),
                        rs.getBoolean("is_read")));
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return messages;
    }

    /**
     * Gets the count of unread system messages.
     * 
     * @return The number of unread system messages
     */
    public static int getUnreadCount() {
        String sql = "SELECT COUNT(*) FROM SystemMessage WHERE is_read = FALSE";
        try (Connection con = DBUtil.getConnection();
                PreparedStatement ps = con.prepareStatement(sql);
                ResultSet rs = ps.executeQuery()) {
            if (rs.next())
                return rs.getInt(1);
        } catch (Exception e) {
            e.printStackTrace();
        }
        return 0;
    }

    /**
     * Marks a system message as read.
     * 
     * @param id The ID of the message to mark as read
     */
    public static void markAsRead(int id) {
        String sql = "UPDATE SystemMessage SET is_read = TRUE WHERE id = ?";
        try (Connection con = DBUtil.getConnection();
                PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Creates a low stock alert for a product.
     * 
     * <p>Creates a system message alerting the owner that a product's stock
     * has fallen below its threshold. Only creates an alert if one doesn't
     * already exist for this product.
     * 
     * @param productId The ID of the product with low stock
     * @param productName The name of the product
     * @param currentStock The current stock level (in kg)
     * @param threshold The stock threshold (in kg)
     */
    public static void createLowStockAlert(int productId, String productName, double currentStock, int threshold) {
        if (alertExistsForProduct(productId))
            return;

        String sql = "INSERT INTO SystemMessage (message_type, title, message, related_product_id) VALUES (?, ?, ?, ?)";
        try (Connection con = DBUtil.getConnection();
                PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setString(1, "LOW_STOCK");
            ps.setString(2, "Low Stock Alert!");
            ps.setString(3, String.format("%s stock has fallen to %.1f kg (Threshold: %d kg)",
                    productName, currentStock, threshold));
            ps.setInt(4, productId);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Checks if a low stock alert already exists for a product.
     * 
     * <p>Checks for unread low stock alerts for the specified product to
     * avoid creating duplicate alerts.
     * 
     * @param productId The product ID to check
     * @return true if an unread low stock alert exists, false otherwise
     */
    private static boolean alertExistsForProduct(int productId) {
        String sql = "SELECT COUNT(*) FROM SystemMessage WHERE related_product_id = ? AND is_read = FALSE AND message_type = 'LOW_STOCK'";
        try (Connection con = DBUtil.getConnection();
                PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, productId);
            try (ResultSet rs = ps.executeQuery()) {
                if (rs.next())
                    return rs.getInt(1) > 0;
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        return false;
    }

    /**
     * Deletes a system message.
     * 
     * @param id The ID of the message to delete
     */
    public static void deleteMessage(int id) {
        String sql = "DELETE FROM SystemMessage WHERE id = ?";
        try (Connection con = DBUtil.getConnection();
                PreparedStatement ps = con.prepareStatement(sql)) {
            ps.setInt(1, id);
            ps.executeUpdate();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * Checks all products and creates low stock alerts where needed.
     * 
     * <p>Retrieves all products with low stock and creates system message
     * alerts for each one that doesn't already have an unread alert.
     */
    public static void checkAndCreateLowStockAlerts() {
        List<model.Product> lowStockProducts = ProductDAO.getLowStockProducts();
        for (model.Product p : lowStockProducts) {
            createLowStockAlert(p.getProductId(), p.getName(), p.getStock(), p.getThreshold());
        }
    }
}
